
export const fnoStocks = [
  { name: "360 ONE WAM Ltd", symbol: "360ONE" },
  { name: "ABB India Ltd", symbol: "ABB" },
  { name: "Adani Energy Solutions Ltd", symbol: "ADANIENSOL" },
  { name: "Adani Enterprises Ltd", symbol: "ADANIENT" },
  { name: "Adani Green Energy Ltd", symbol: "ADANIGREEN" },
  { name: "Adani Ports & Special Economic Zone Ltd", symbol: "ADANIPORTS" },
  { name: "Adani Power Ltd", symbol: "ADANIPOWER" },
  { name: "Aditya Birla Capital Ltd", symbol: "ABCAPITAL" },
  { name: "Alkem Laboratories Ltd", symbol: "ALKEM" },
  { name: "Amber Enterprises India Ltd", symbol: "AMBER" },
  { name: "Ambuja Cements Ltd", symbol: "AMBUJACEM" },
  { name: "Angel One Ltd", symbol: "ANGELONE" },
  { name: "APL Apollo Tubes Ltd", symbol: "APLAPOLLO" },
  { name: "Apollo Hospitals Enterprise Ltd", symbol: "APOLLOHOSP" },
  { name: "Ashok Leyland Ltd", symbol: "ASHOKLEY" },
  { name: "Asian Paints Ltd", symbol: "ASIANPAINT" },
  { name: "Astral Ltd", symbol: "ASTRAL" },
  { name: "AU Small Finance Bank Ltd", symbol: "AUBANK" },
  { name: "Aurobindo Pharma Ltd", symbol: "AUROPHARMA" },
  { name: "Avenue Supermarts Ltd", symbol: "DMART" },
  { name: "Axis Bank Ltd", symbol: "AXISBANK" },
  { name: "Bajaj Auto Ltd", symbol: "BAJAJ-AUTO" },
  { name: "Bajaj Finance Ltd", symbol: "BAJFINANCE" },
  { name: "Bajaj Finserv Ltd", symbol: "BAJAJFINSV" },
  { name: "Bajaj Holdings & Investment Ltd", symbol: "BAJAJHLDNG" },
  { name: "Bandhan Bank Ltd", symbol: "BANDHANBNK" },
  { name: "Bank of Baroda", symbol: "BANKBARODA" },
  { name: "Bank of India", symbol: "BANKINDIA" },
  { name: "Bharat Dynamics Ltd", symbol: "BDL" },
  { name: "Bharat Electronics Ltd", symbol: "BEL" },
  { name: "Bharat Forge Ltd", symbol: "BHARATFORG" },
  { name: "Bharat Heavy Electricals Ltd", symbol: "BHEL" },
  { name: "Bharat Petroleum Corporation Ltd", symbol: "BPCL" },
  { name: "Bharti Airtel Ltd", symbol: "BHARTIARTL" },
  { name: "Biocon Ltd", symbol: "BIOCON" },
  { name: "Blue Star Ltd", symbol: "BLUESTARCO" },
  { name: "Bosch Ltd", symbol: "BOSCHLTD" },
  { name: "Britannia Industries Ltd", symbol: "BRITANNIA" },
  { name: "BSE Ltd", symbol: "BSE" },
  { name: "Canara Bank", symbol: "CANBK" },
  { name: "Central Depository Services (India) Ltd", symbol: "CDSL" },
  { name: "CG Power & Industrial Solutions Ltd", symbol: "CGPOWER" },
  { name: "Cholamandalam Investment & Finance Company Ltd", symbol: "CHOLAFIN" },
  { name: "Cipla Ltd", symbol: "CIPLA" },
  { name: "Coal India Ltd", symbol: "COALINDIA" },
  { name: "Cochin Shipyard Ltd", symbol: "COCHINSHIP" },
  { name: "Coforge Ltd", symbol: "COFORGE" },
  { name: "Colgate-Palmolive (India) Ltd", symbol: "COLPAL" },
  { name: "Computer Age Management Services Ltd", symbol: "CAMS" },
  { name: "Container Corporation Of India Ltd", symbol: "CONCOR" },
  { name: "Crompton Greaves Consumer Electricals Ltd", symbol: "CROMPTON" },
  { name: "Cummins India Ltd", symbol: "CUMMINSIND" },
  { name: "Dabur India Ltd", symbol: "DABUR" },
  { name: "Dalmia Bharat Ltd", symbol: "DALBHARAT" },
  { name: "Delhivery Ltd", symbol: "DELHIVERY" },
  { name: "Divis Laboratories Ltd", symbol: "DIVISLAB" },
  { name: "Dixon Technologies (India) Ltd", symbol: "DIXON" },
  { name: "DLF Ltd", symbol: "DLF" },
  { name: "Dr Reddys Laboratories Ltd", symbol: "DRREDDY" },
  { name: "Eicher Motors Ltd", symbol: "EICHERMOT" },
  { name: "Exide Industries Ltd", symbol: "EXIDEIND" },
  { name: "Federal Bank Ltd", symbol: "FEDERALBNK" },
  { name: "Force Motors Ltd", symbol: "FORCEMOT" },
  { name: "Fortis Healthcare Ltd", symbol: "FORTIS" },
  { name: "FSN E-Commerce Ventures Ltd", symbol: "NYKAA" },
  { name: "GAIL (India) Ltd", symbol: "GAIL" },
  { name: "Glenmark Pharmaceuticals Ltd", symbol: "GLENMARK" },
  { name: "GMR Airports Ltd", symbol: "GMRINFRA" },
  { name: "Godfrey Phillips India Ltd", symbol: "GODFRYPHLP" },
  { name: "Godrej Consumer Products Ltd", symbol: "GODREJCP" },
  { name: "Godrej Properties Ltd", symbol: "GODREJPROP" },
  { name: "Grasim Industries Ltd", symbol: "GRASIM" },
  { name: "Havells India Ltd", symbol: "HAVELLS" },
  { name: "HCL Technologies Ltd", symbol: "HCLTECH" },
  { name: "HDFC Asset Management Company Ltd", symbol: "HDFCAMC" },
  { name: "HDFC Bank Ltd", symbol: "HDFCBANK" },
  { name: "HDFC Life Insurance Company Ltd", symbol: "HDFCLIFE" },
  { name: "Hero MotoCorp Ltd", symbol: "HEROMOTOCO" },
  { name: "Hindalco Industries Ltd", symbol: "HINDALCO" },
  { name: "Hindustan Aeronautics Ltd", symbol: "HAL" },
  { name: "Hindustan Petroleum Corporation Ltd", symbol: "HPCL" },
  { name: "Hindustan Unilever Ltd", symbol: "HINDUNILVR" },
  { name: "Hindustan Zinc Ltd", symbol: "HINDZINC" },
  { name: "Hitachi Energy India Ltd", symbol: "HITACHI" },
  { name: "Housing & Urban Development Corporation Ltd", symbol: "HUDCO" },
  { name: "Hyundai Motor India Ltd", symbol: "HYUNDAI" },
  { name: "ICICI Bank Ltd", symbol: "ICICIBANK" },
  { name: "ICICI Lombard General Insurance Company Ltd", symbol: "ICICIGI" },
  { name: "ICICI Prudential Life Insurance Company Ltd", symbol: "ICICIPRULI" },
  { name: "IDFC First Bank Ltd", symbol: "IDFCFIRSTB" },
  { name: "Indian Bank", symbol: "INDIANB" },
  { name: "Indian Energy Exchange Ltd", symbol: "IEX" },
  { name: "Indian Hotels Co Ltd", symbol: "INDHOTEL" },
  { name: "Indian Oil Corporation Ltd", symbol: "IOC" },
  { name: "Indian Railway Finance Corporation Ltd", symbol: "IRFC" },
  { name: "Indian Renewable Energy Development Agency Ltd", symbol: "IREDA" },
  { name: "Indus Towers Ltd", symbol: "INDUSTOWER" },
  { name: "IndusInd Bank Ltd", symbol: "INDUSINDBK" },
  { name: "Info Edge (India) Ltd", symbol: "NAUKRI" },
  { name: "Infosys Ltd", symbol: "INFY" },
  { name: "Inox Wind Ltd", symbol: "INOXWIND" },
  { name: "Interglobe Aviation Ltd", symbol: "INDIGO" },
  { name: "ITC Ltd", symbol: "ITC" },
  { name: "Jindal Steel Ltd", symbol: "JSL" },
  { name: "Jio Financial Services Ltd", symbol: "JIOFIN" },
  { name: "JSW Energy Ltd", symbol: "JSWENERGY" },
  { name: "JSW Steel Ltd", symbol: "JSWSTEEL" },
  { name: "Jubilant Foodworks Ltd", symbol: "JUBLFOOD" },
  { name: "Kalyan Jewellers India Ltd", symbol: "KALYANKJIL" },
  { name: "Kaynes Technology India Ltd", symbol: "KAYNES" },
  { name: "KEI Industries Ltd", symbol: "KEI" },
  { name: "KFin Technologies Ltd", symbol: "KFINTECH" },
  { name: "Kotak Mahindra Bank Ltd", symbol: "KOTAKBANK" },
  { name: "KPIT Technologies Ltd", symbol: "KPITTECH" },
  { name: "L&T Finance Ltd", symbol: "LTF" },
  { name: "Larsen & Toubro Ltd", symbol: "LT" },
  { name: "Laurus Labs Ltd", symbol: "LAURUSLABS" },
  { name: "LIC Housing Finance Ltd", symbol: "LICHSGFIN" },
  { name: "Life Insurance Corporation of India", symbol: "LICI" },
  { name: "Lodha Developers Ltd", symbol: "LODHA" },
  { name: "LTM Ltd", symbol: "LTM" },
  { name: "Lupin Ltd", symbol: "LUPIN" },
  { name: "Mahindra & Mahindra Ltd", symbol: "M&M" },
  { name: "Manappuram Finance Ltd", symbol: "MANAPPURAM" },
  { name: "Mankind Pharma Ltd", symbol: "MANKIND" },
  { name: "Marico Ltd", symbol: "MARICO" },
  { name: "Maruti Suzuki India Ltd", symbol: "MARUTI" },
  { name: "Max Financial Services Ltd", symbol: "MAXF" },
  { name: "Max Healthcare Institute Ltd", symbol: "MAXHEALTH" },
  { name: "Mazagon Dock Shipbuilders Ltd", symbol: "MAZDOCK" },
  { name: "Motilal Oswal Financial Services Ltd", symbol: "MOTILALOFS" },
  { name: "Mphasis Ltd", symbol: "MPHASIS" },
  { name: "Multi Commodity Exchange of India Ltd", symbol: "MCX" },
  { name: "Muthoot Finance Ltd", symbol: "MUTHOOTFIN" },
  { name: "National Aluminium Company Ltd", symbol: "NATIONALUM" },
  { name: "NBCC (India) Ltd", symbol: "NBCC" },
  { name: "Nestle India Ltd", symbol: "NESTLEIND" },
  { name: "NHPC Ltd", symbol: "NHPC" },
  { name: "Nippon Life India Asset Management Ltd", symbol: "NAM-INDIA" },
  { name: "NMDC Ltd", symbol: "NMDC" },
  { name: "NTPC Ltd", symbol: "NTPC" },
  { name: "Nuvama Wealth Management Ltd", symbol: "NUVAMA" },
  { name: "Oberoi Realty Ltd", symbol: "OBEROIRLTY" },
  { name: "Oil & Natural Gas Corpn Ltd", symbol: "ONGC" },
  { name: "Oil India Ltd", symbol: "OIL" },
  { name: "One 97 Communications Ltd", symbol: "PAYTM" },
  { name: "Oracle Financial Services Software Ltd", symbol: "OFSS" },
  { name: "P I Industries Ltd", symbol: "PIIND" },
  { name: "Page Industries Ltd", symbol: "PAGEIND" },
  { name: "Patanjali Foods Ltd", symbol: "PATANJALI" },
  { name: "PB Fintech Ltd", symbol: "PBFINTECH" },
  { name: "Persistent Systems Ltd", symbol: "PERSISTENT" },
  { name: "Petronet LNG Ltd", symbol: "PETRONET" },
  { name: "PG Electroplast Ltd", symbol: "PGEL" },
  { name: "Phoenix Mills Ltd", symbol: "PHOENIXLTD" },
  { name: "Pidilite Industries Ltd", symbol: "PIDILITIND" },
  { name: "Piramal Pharma Ltd", symbol: "PPLPHARMA" },
  { name: "PNB Housing Finance Ltd", symbol: "PNBHOUSING" },
  { name: "Polycab India Ltd", symbol: "POLYCAB" },
  { name: "Power Finance Corporation Ltd", symbol: "PFC" },
  { name: "Power Grid Corporation of India Ltd", symbol: "POWERGRID" },
  { name: "Premier Energies Ltd", symbol: "PREMIERENE" },
  { name: "Prestige Estates Projects Ltd", symbol: "PRESTIGE" },
  { name: "Punjab National Bank", symbol: "PNB" },
  { name: "Rail Vikas Nigam Ltd", symbol: "RVNL" },
  { name: "RBL Bank Ltd", symbol: "RBLBANK" },
  { name: "REC Ltd", symbol: "REC" },
  { name: "Reliance Industries Ltd", symbol: "RELIANCE" },
  { name: "Sammaan Capital Ltd", symbol: "SAMMAAN" },
  { name: "Samvardhana Motherson International Ltd", symbol: "MOTHERSON" },
  { name: "SBI Cards & Payment Services Ltd", symbol: "SBICARD" },
  { name: "SBI Life Insurance Company Ltd", symbol: "SBILIFE" },
  { name: "Shree Cement Ltd", symbol: "SHREECEM" },
  { name: "Shriram Finance Ltd", symbol: "SHRIRAMFIN" },
  { name: "Siemens Ltd", symbol: "SIEMENS" },
  { name: "Solar Industries India Ltd", symbol: "SOLARINDS" },
  { name: "Sona BLW Precision Forgings Ltd", symbol: "SONACOMS" },
  { name: "SRF Ltd", symbol: "SRF" },
  { name: "State Bank of India", symbol: "SBIN" },
  { name: "Steel Authority of India Ltd", symbol: "SAIL" },
  { name: "Sun Pharmaceutical Industries Ltd", symbol: "SUNPHARMA" },
  { name: "Supreme Industries Ltd", symbol: "SUPREMEIND" },
  { name: "Suzlon Energy Ltd", symbol: "SUZLON" },
  { name: "Swiggy Ltd", symbol: "SWIGGY" },
  { name: "Tata Consultancy Services Ltd", symbol: "TCS" },
  { name: "Tata Consumer Products Ltd", symbol: "TATACONSUM" },
  { name: "Tata Elxsi Ltd", symbol: "TATAELXSI" },
  { name: "Tata Motors Passenger Vehicles Ltd", symbol: "TATAMOTORS" },
  { name: "Tata Power Company Ltd", symbol: "TATAPOWER" },
  { name: "Tata Steel Ltd", symbol: "TATASTEEL" },
  { name: "Tata Technologies Ltd", symbol: "TATATECH" },
  { name: "Tech Mahindra Ltd", symbol: "TECHM" },
  { name: "Titan Company Ltd", symbol: "TITAN" },
  { name: "Torrent Pharmaceuticals Ltd", symbol: "TORNTPHARM" },
  { name: "Torrent Power Ltd", symbol: "TORNTPOWER" },
  { name: "Trent Ltd", symbol: "TRENT" },
  { name: "Tube Investments of India Ltd", symbol: "TIINDIA" },
  { name: "TVS Motor Company Ltd", symbol: "TVSMOTOR" },
  { name: "UltraTech Cement Ltd", symbol: "ULTRACEMCO" },
  { name: "Union Bank of India", symbol: "UNIONBANK" },
  { name: "United Spirits Ltd", symbol: "UNITDSPR" },
  { name: "Uno Minda Ltd", symbol: "UNOMINDA" },
  { name: "UPL Ltd", symbol: "UPL" },
  { name: "Varun Beverages Ltd", symbol: "VBL" },
  { name: "Vedanta Ltd", symbol: "VEDL" },
  { name: "Vodafone Idea Ltd", symbol: "IDEA" },
  { name: "Voltas Ltd", symbol: "VOLTAS" },
  { name: "Waaree Energies Ltd", symbol: "WAAREEENER" },
  { name: "Wipro Ltd", symbol: "WIPRO" },
  { name: "Yes Bank Ltd", symbol: "YESBANK" },
  { name: "Zydus Lifesciences Ltd", symbol: "ZYDUSLIFE" }
];
