/**
 * @fileoverview Library of standard Nifty Index constituents.
 * These lists are based on the latest NSE rebalances (2024).
 */

export const NIFTY_50 = [
  "ADANIENT", "ADANIPORTS", "APOLLOHOSP", "ASIANPAINT", "AXISBANK", "BAJAJ-AUTO", "BAJFINANCE", "BAJAJFINSV", "BPCL", "BHARTIARTL", 
  "BRITANNIA", "CIPLA", "COALINDIA", "DIVISLAB", "DRREDDY", "EICHERMOT", "GRASIM", "HCLTECH", "HDFCBANK", "HDFCLIFE", 
  "HEROMOTOCO", "HINDALCO", "HINDUNILVR", "ICICIBANK", "INDUSINDBK", "INFY", "ITC", "JSWSTEEL", "KOTAKBANK", "LT", 
  "LTIM", "M&M", "MARUTI", "NESTLEIND", "NTPC", "ONGC", "POWERGRID", "RELIANCE", "SBILIFE", "SBIN", 
  "SUNPHARMA", "TATACONSUM", "TATAMOTORS", "TATASTEEL", "TCS", "TECHM", "TITAN", "ULTRACEMCO", "UPL", "WIPRO"
];

export const NIFTY_NEXT_50 = [
  "ABB", "ABCAPITAL", "ABFRL", "ADANIENSOL", "ADANIGREEN", "ADANIPOWER", "ALKEM", "AMBUJACEM", "AUROPHARMA", "DMART", 
  "BANKBARODA", "BEL", "BERGEPAINT", "BIOCON", "CANBK", "CHOLAFIN", "COLPAL", "CONCOR", "DLF", "DABUR", 
  "GAIL", "GODREJCP", "HAL", "HAVELLS", "ICICIGI", "ICICIPRULI", "IOC", "IRCTC", "INDIGO", "JINDALSTEL", 
  "JIOFIN", "LICI", "LUPIN", "MARICO", "MCDOWELL-N", "MUTHOOTFIN", "NMDC", "NYKAA", "PIIND", "PIDILITIND", 
  "PFC", "PGHH", "PNB", "RECLTD", "SHREECEM", "SRF", "TATAELXSI", "TRENT", "VBL", "VEDL", "ZOMATO"
];

export const MIDCAP_SELECT = [
  "ABCAPITAL", "AUROPHARMA", "BALKRISIND", "BANDHANBNK", "BHARATFORG", "COFORGE", "CUMMINSIND", "DIXON", "ESCORTS", "FEDERALBNK", 
  "FORTIS", "GODREJPROP", "GUJGASLTD", "IDFCFIRSTB", "INDIACEM", "INDHOTEL", "IPCALAB", "JINDALSTEL", "JUBLFOOD", "KPITTECH", 
  "L&TFH", "LAURUSLABS", "LICHSGFIN", "LUPIN", "M&MFIN", "MRF", "OBEROIRLTY", "PEL", "PERSISTENT", "POLYCAB", 
  "SHRIRAMFIN", "TATACOMM", "TVSMOTOR", "VOLTAS", "ZEEL"
];

export const MIDCAP_150_CORE = [
  "AAVAS", "ABFRL", "AEGISLOG", "AETHER", "AFFLE", "AJANTPHARM", "ALKEM", "AMBER", "ANGELONE", "APLLTD", 
  "APOLLOTYRE", "APTUS", "ASHOKA", "ASTRAL", "AUBANK", "AVANTIFEED", "BALAMINES", "BALKRISIND", "BANDHANBNK", "BANKINDIA", 
  "BATAINDIA", "BEL", "BHEL", "BIRLACORPN", "BLUESTARCO", "BOSCHLTD", "CANFINHOME", "CAMS", "CEATLTD", "CENTRALBK", 
  "CGPOWER", "CHAMBLFERT", "CHOLAFIN", "CLEAN", "COFORGE", "COROMANDEL", "CRAFTSMAN", "CROMPTON", "CUMMINSIND", "CYIENT", 
  "DALBHARAT", "DATAPATTNS", "DEEPAKNTR", "DELHIVERY", "DEVYANI", "DIXON", "EMAMILTD", "ENDURANCE", "ESCORTS", "EXIDEIND", 
  "FEDERALBNK", "FORTIS", "FSL", "GLENMARK", "GMRINFRA", "GODREJPROP", "GRINFRA", "GUJGASLTD", "HAPPSTMNDS", "HDFCAMC", 
  "HFIN", "HINDCOPPER", "HINDPETRO", "HONAUT", "HUDCO", "IDFC", "IDFCFIRSTB", "IEX", "IGL", "INDHOTEL", 
  "INDIACEM", "INDIAMART", "INDIANB", "INDIGOPNTS", "INDUSTOWER", "IPCALAB", "IRB", "IRCON", "ITI", "JBCHEPHARM", 
  "JKCEMENT", "JSL", "JUBLFOOD", "KALYANKJIL", "KEC", "KEI", "KPITTECH", "KPRMILL", "KRBL", "L&TFH", 
  "LAURUSLABS", "LICHSGFIN", "LODHA", "LUPIN", "LXCHEM", "M&MFIN", "MAHABANK", "MAHLOG", "MANAPPURAM", "MANYAVAR", 
  "MAPMYINDIA", "MARICO", "MAXHEALTH", "MAZDOCK", "MCX", "METROPOLIS", "MFSL", "MGL", "MINDACORP", "MOTILALOFS", 
  "MPHASIS", "MTARTECH", "NAM-INDIA", "NATIONALUM", "NAUKRI", "NAVINFLUOR", "NAZARA", "NHPC", "NLCINDIA", "NMDC", 
  "NUVOCO", "OBEROIRLTY", "OFSS", "OIL", "PAGEIND", "PATANJALI", "PEL", "PERSISTENT", "PETRONET", "PHOENIXLTD", 
  "POLYCAB", "POONAWALLA", "PRESTIGE", "QUESS", "RAILTEL", "RAJESHEXPO", "RAMCOCEM", "RATNAMANI", "RBLBANK", "RELAXO", 
  "RVNL", "SJVN", "SKFINDIA", "SONACOMS", "STARHEALTH", "SUNTECK", "SUPRAJIT", "SYNGENE", "TATACOMM", "TATAELXSI", 
  "TATATECH", "TEAMLEASE", "THERMAX", "TIINDIA", "TRIDENT", "TRITURBINE", "TVSMOTOR", "UNIONBANK", "UNOMINDA", "VGUARD", 
  "VIJAYA", "VINATIORGA", "VOLTAS", "WHIRLPOOL", "YESBANK", "ZEEL", "ZYDUSLIFE"
];
